# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: checkLeader.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'checkLeader.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11\x63heckLeader.proto\"&\n\x12\x43heckLeaderRequest\x12\x10\n\x08\x63lientID\x18\x01 \x01(\t\";\n\x13\x43heckLeaderResponse\x12\x10\n\x08isLeader\x18\x01 \x01(\x08\x12\x12\n\nleaderPort\x18\x02 \x01(\t2P\n\x12\x43heckLeaderService\x12:\n\x0b\x43heckLeader\x12\x13.CheckLeaderRequest\x1a\x14.CheckLeaderResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'checkLeader_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CHECKLEADERREQUEST']._serialized_start=21
  _globals['_CHECKLEADERREQUEST']._serialized_end=59
  _globals['_CHECKLEADERRESPONSE']._serialized_start=61
  _globals['_CHECKLEADERRESPONSE']._serialized_end=120
  _globals['_CHECKLEADERSERVICE']._serialized_start=122
  _globals['_CHECKLEADERSERVICE']._serialized_end=202
# @@protoc_insertion_point(module_scope)
