# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sendMessage.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'sendMessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11sendMessage.proto\"%\n\x12SendMessageRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"=\n\x13SendMessageResponse\x12\x14\n\x0cisSuccessful\x18\x01 \x01(\x08\x12\x10\n\x08isLeader\x18\x02 \x01(\x08\x32P\n\x12SendMessageService\x12:\n\x0bSendMessage\x12\x13.SendMessageRequest\x1a\x14.SendMessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sendMessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SENDMESSAGEREQUEST']._serialized_start=21
  _globals['_SENDMESSAGEREQUEST']._serialized_end=58
  _globals['_SENDMESSAGERESPONSE']._serialized_start=60
  _globals['_SENDMESSAGERESPONSE']._serialized_end=121
  _globals['_SENDMESSAGESERVICE']._serialized_start=123
  _globals['_SENDMESSAGESERVICE']._serialized_end=203
# @@protoc_insertion_point(module_scope)
